from pathlib import Path

DATA_PATH = Path("data") / "100" / "Batch1"


CASH_TRANSACTION_FILE_PATH = DATA_PATH / "CashTransaction.txt"
CUSTOMER_MGMT_FILE_PATH = DATA_PATH / "CustomerMgmt.xml"
DAILY_MARKET_FILE_PATH = DATA_PATH / "DailyMarket.txt"
DATE_FILE_PATH = DATA_PATH / "Date.txt"
FINWIRE_FILES_PATH = DATA_PATH / "FINWIRE1974Q1"#[1-2][0-9][0-9][0-9]Q[1-4]"
HOLDING_HISTORY_FILE_PATH = DATA_PATH / "HoldingHistory.txt"
HR_FILE_PATH = DATA_PATH / "HR.csv"
INDUSTRY_FILE_PATH = DATA_PATH / "Industry.txt"
PROSPECT_FILE_PATH = DATA_PATH / "Prospect.csv"
STATUS_TYPE_FILE_PATH = DATA_PATH / "StatusType.txt"
TAX_RATE_FILE_PATH = DATA_PATH / "TaxRate.txt"
TIME_FILE_PATH = DATA_PATH / "Time.txt"
TRADE_FILE_PATH = DATA_PATH / "Trade.txt"
TRADE_HISTORY_FILE_PATH = DATA_PATH / "TradeHistory.txt"
TRADE_TYPE_FILE_PATH = DATA_PATH / "TradeType.txt"
WATCH_HISTORY_FILE_PATH = DATA_PATH / "WatchHistory.txt"
